var a = {
	"license_title" : "Creative Commons CCZero",
	"maintainer" : "Provincia di Roma",
	"maintainer_email" : "",
	"id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
	"metadata_created" : "2012-03-15T10:04:33.568356",
	"relationships" : [],
	"license" : "Creative Commons CCZero",
	"metadata_modified" : "2012-10-11T13:01:35.617305",
	"author" : "Provincia di Roma",
	"author_email" : "",
	"download_url" : "http://85.18.173.117/opendata/PareriNegativiConFrequenza.xml",
	"state" : "active",
	"version" : "",
	"license_id" : "cc-zero",
	"type" : null,
	"resources" : [ {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "d541872b-521f-46f0-9d96-83e1241342e5",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "I 10 pareri negativi pi\u00f9 frequenti nel 2011",
		"format" : "xml",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "xml",
		"mimetype" : "xml",
		"cache_url" : null,
		"name" : "I 10 pareri negativi pi\u00f9 frequenti nel 2011",
		"created" : null,
		"url" : "http://85.18.173.117/opendata/PareriNegativiConFrequenza.xml",
		"webstore_url" : "",
		"position" : 0,
		"resource_type" : "file"
	}, {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "07b56077-6e53-4e83-b761-01c52be919c4",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "Le 10 nazionalit\u00e0 straniere pi\u00f9 frequenti tra i pareri positivi del 2011",
		"format" : "xml",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "xml",
		"mimetype" : "xml",
		"cache_url" : null,
		"name" : "Le 10 nazionalit\u00e0 straniere pi\u00f9 frequenti tra i pareri positivi del 2011",
		"created" : null,
		"url" : "	",
		"webstore_url" : "",
		"position" : 1,
		"resource_type" : "file"
	}, {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "634e66b7-73eb-4f4e-91c7-39d8fe8b36c4",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "Le 10 qualifiche pi\u00f9 frequenti tra i pareri positivi del 2011",
		"format" : "xml",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "xml",
		"mimetype" : "xml",
		"cache_url" : null,
		"name" : "Le 10 qualifiche pi\u00f9 frequenti tra i pareri positivi del 2011",
		"created" : null,
		"url" : "http://85.18.173.117/opendata/PareriSuddivisiPerQualifica.xml",
		"webstore_url" : "",
		"position" : 2,
		"resource_type" : "file"
	}, {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "1e1433aa-f06b-413d-9c4a-7b8950efe1ec",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "Suddivisione delle richieste del 2011 per trimestre e per parere",
		"format" : "xml",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "xml",
		"mimetype" : "xml",
		"cache_url" : null,
		"name" : "Suddivisione delle richieste del 2011 per trimestre e per parere",
		"created" : null,
		"url" : "http://85.18.173.117/opendata/SuddivisionePerTrimestre.xml",
		"webstore_url" : "",
		"position" : 3,
		"resource_type" : "file"
	}, {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "b9c5b239-a13f-4773-bc5e-1a0165e05439",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "CSV - I 10 pareri negativi pi\u00f9 frequenti nel 2011",
		"format" : "csv",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "csv",
		"mimetype" : "csv",
		"cache_url" : null,
		"name" : "CSV - I 10 pareri negativi pi\u00f9 frequenti nel 2011",
		"created" : null,
		"url" : "http://85.18.173.117/opendata/PareriNegativiConFrequenza.csv",
		"webstore_url" : "",
		"position" : 4,
		"resource_type" : "file"
	}, {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "97de4786-2e47-470e-adc9-5426dd26082f",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "CSV - Le 10 nazionalit\u00e0 straniere pi\u00f9 frequenti tra i pareri positivi del 2011",
		"format" : "csv",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "csv",
		"mimetype" : "csv",
		"cache_url" : null,
		"name" : "CSV - Le 10 nazionalit\u00e0 straniere pi\u00f9 frequenti tra i pareri positivi del 2011",
		"created" : null,
		"url" : "http://85.18.173.117/opendata/PareriSuddivisiPerNazionalita.csv",
		"webstore_url" : "",
		"position" : 5,
		"resource_type" : "file"
	}, {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "c8a48176-aff4-4b56-ba6a-b8aac36cccd8",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "CSV - Le 10 qualifiche pi\u00f9 frequenti tra i pareri positivi del 2011",
		"format" : "csv",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "csv",
		"mimetype" : "csv",
		"cache_url" : null,
		"name" : "CSV - Le 10 qualifiche pi\u00f9 frequenti tra i pareri positivi del 2011",
		"created" : null,
		"url" : "http://85.18.173.117/opendata/PareriSuddivisiPerQualifica.csv",
		"webstore_url" : "",
		"position" : 6,
		"resource_type" : "file"
	}, {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "e6f38fc0-1a7b-4174-adc2-9e652a621305",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "CSV - Suddivisione delle richieste del 2011 per trimestre e per parere",
		"format" : "csv",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "csv",
		"mimetype" : "csv",
		"cache_url" : null,
		"name" : "CSV - Suddivisione delle richieste del 2011 per trimestre e per parere",
		"created" : null,
		"url" : "http://85.18.173.117/opendata/SuddivisionePerTrimestre.csv",
		"webstore_url" : "",
		"position" : 7,
		"resource_type" : "file"
	}, {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "2c7d9188-5429-44ee-9a46-88787c3259a0",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "CSV Excel Ita - I 10 pareri negativi pi\u00f9 frequenti nel 2011",
		"format" : "csv",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "csv",
		"mimetype" : "csv",
		"cache_url" : null,
		"name" : "CSV Excel Ita - I 10 pareri negativi pi\u00f9 frequenti nel 2011",
		"created" : null,
		"url" : "http://85.18.173.117/opendata/PareriNegativiConFrequenzaExIta.csv",
		"webstore_url" : "",
		"position" : 8,
		"resource_type" : "file"
	}, {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "dc237560-1f85-4be2-8c9c-292b034d1934",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "CSV Excel Ita - Le 10 nazionalit\u00e0 straniere pi\u00f9 frequenti tra i pareri positivi del 2011",
		"format" : "csv",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "csv",
		"mimetype" : "csv",
		"cache_url" : null,
		"name" : "CSV Excel Ita - Le 10 nazionalit\u00e0 straniere pi\u00f9 frequenti tra i pareri positivi del 2011",
		"created" : null,
		"url" : "http://85.18.173.117/opendata/PareriSuddivisiPerNazionalitaExIta.csv",
		"webstore_url" : "",
		"position" : 9,
		"resource_type" : "file"
	}, {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "17a6f5ab-5826-4f8b-807a-981c3bcabf65",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "CSV Excel Ita - Le 10 qualifiche pi\u00f9 frequenti tra i pareri positivi del 2011",
		"format" : "csv",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "csv",
		"mimetype" : "csv",
		"cache_url" : null,
		"name" : "CSV Excel Ita - Le 10 qualifiche pi\u00f9 frequenti tra i pareri positivi del 2011",
		"created" : null,
		"url" : "http://85.18.173.117/opendata/PareriSuddivisiPerQualificaExIta.csv",
		"webstore_url" : "",
		"position" : 10,
		"resource_type" : "file"
	}, {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "127558d5-d635-4ff6-9e57-252e393d6d8f",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "CSV Excel Ita - Suddivisione delle richieste del 2011 per trimestre e per parere",
		"format" : "csv",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "csv",
		"mimetype" : "csv",
		"cache_url" : null,
		"name" : "CSV Excel Ita - Suddivisione delle richieste del 2011 per trimestre e per parere",
		"created" : null,
		"url" : "http://85.18.173.117/opendata/SuddivisionePerTrimestreExIta.csv",
		"webstore_url" : "",
		"position" : 11,
		"resource_type" : "file"
	}, {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "ab862f69-49f9-4120-824e-b50ec70a6f7e",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "TSV - I 10 pareri negativi pi\u00f9 frequenti nel 2011",
		"format" : "tsv",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "tsv",
		"mimetype" : "tsv",
		"cache_url" : null,
		"name" : "TSV - I 10 pareri negativi pi\u00f9 frequenti nel 2011",
		"created" : null,
		"url" : "http://85.18.173.117/opendata/PareriNegativiConFrequenza.tsv",
		"webstore_url" : "",
		"position" : 12,
		"resource_type" : "file"
	}, {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "50f65c6c-9aca-4af1-ad32-8c28c8dd75ea",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "TSV - Le 10 nazionalit\u00e0 straniere pi\u00f9 frequenti tra i pareri positivi del 2011",
		"format" : "tsv",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "tsv",
		"mimetype" : "tsv",
		"cache_url" : null,
		"name" : "TSV - Le 10 nazionalit\u00e0 straniere pi\u00f9 frequenti tra i pareri positivi del 2011",
		"created" : null,
		"url" : "http://85.18.173.117/opendata/PareriSuddivisiPerNazionalita.tsv",
		"webstore_url" : "",
		"position" : 13,
		"resource_type" : "file"
	}, {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "6d1a8057-e3df-40ee-957d-dbcf11402e59",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "TSV - Le 10 qualifiche pi\u00f9 frequenti tra i pareri positivi del 2011",
		"format" : "tsv",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "tsv",
		"mimetype" : "tsv",
		"cache_url" : null,
		"name" : "TSV - Le 10 qualifiche pi\u00f9 frequenti tra i pareri positivi del 2011",
		"created" : null,
		"url" : "http://85.18.173.117/opendata/PareriSuddivisiPerQualifica.tsv",
		"webstore_url" : "",
		"position" : 14,
		"resource_type" : "file"
	}, {
		"resource_group_id" : "52d0b92a-990f-4a60-bc06-aa69fbcd8877",
		"cache_last_updated" : null,
		"package_id" : "ff3d13ff-c14d-403e-947b-05cb53d24efe",
		"webstore_last_updated" : null,
		"id" : "70e3de2a-a821-4688-8273-27ce6d255093",
		"size" : null,
		"last_modified" : null,
		"hash" : "",
		"description" : "TSV - Suddivisione delle richieste del 2011 per trimestre e per parere",
		"format" : "tsv",
		"tracking_summary" : {
			"total" : 0,
			"recent" : 0
		},
		"mimetype_inner" : "tsv",
		"mimetype" : "tsv",
		"cache_url" : null,
		"name" : "TSV - Suddivisione delle richieste del 2011 per trimestre e per parere",
		"created" : null,
		"url" : "http://85.18.173.117/opendata/SuddivisionePerTrimestre.tsv",
		"webstore_url" : "",
		"position" : 15,
		"resource_type" : "file"
	} ],
	"tags" : [ "apprendistato", "assunzioni", "parere-di-conformit\u00e0" ],
	"tracking_summary" : {
		"total" : 0,
		"recent" : 0
	},
	"groups" : [ "lavoro-e-formazione" ],
	"name" : "richieste-parere-di-conformit-per-le-assunzioni-in-apprendistato",
	"isopen" : true,
	"notes_rendered" : "<p>Prima di poter procedere ad una assunzione in apprendistato professionalizzante, l'azienda \u00e8 tenuta a richiedere il parere di conformit\u00e0 alla commissione provinciale o all'Ente bilaterale ove previsto dal Contratto Collettivo Nazionale. In mancanza di tale parere, o in caso di parere negativo, non sar\u00e0 possibile procedere all'assunzione.\n</p>\n<p>COSA TROVI NEL DATASET: Dati statistici sulle richieste di parere di conformit\u00e0 arrivate ai Centri per l'Impiego nel 2011\n</p>",
	"url" : "",
	"ckan_url" : "http://www.opendata.provincia.roma.it/dataset/richieste-parere-di-conformit-per-le-assunzioni-in-apprendistato",
	"notes" : "Prima di poter procedere ad una assunzione in apprendistato professionalizzante, l'azienda \u00e8 tenuta a richiedere il parere di conformit\u00e0 alla commissione provinciale o all'Ente bilaterale ove previsto dal Contratto Collettivo Nazionale. In mancanza di tale parere, o in caso di parere negativo, non sar\u00e0 possibile procedere all'assunzione.\r\n\r\nCOSA TROVI NEL DATASET: Dati statistici sulle richieste di parere di conformit\u00e0 arrivate ai Centri per l'Impiego nel 2011",
	"title" : "Richieste parere di conformit\u00e0 per le assunzioni in apprendistato",
	"ratings_average" : null,
	"extras" : {},
	"license_url" : "http://www.opendefinition.org/licenses/cc-zero",
	"ratings_count" : 0,
	"revision_id" : "341ad04a-2784-4ac8-bf07-e6094f1ca3b1"
}